In [1]:
import pandas as pd

In [2]:
csv_file_path = 'imdb_1000.csv'
df = pd.read_csv(csv_file_path)

In [3]:
df.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [4]:
df[['title']]

                                                 title
0                             The Shawshank Redemption
1                                        The Godfather
2                               The Godfather: Part II
3                                      The Dark Knight
4                                         Pulp Fiction
5                                         12 Angry Men
6                       The Good, the Bad and the Ugly
7        The Lord of the Rings: The Return of the King
8                                     Schindler's List
9                                           Fight Club
10   The Lord of the Rings: The Fellowship of the Ring
11                                           Inception
12      Star Wars: Episode V - The Empire Strikes Back
13                                        Forrest Gump
14               The Lord of the Rings: The Two Towers
15                                        Interstellar
16                     One Flew Over the Cuckoo's Nest
17                                       Seven Samurai
18                                          Goodfellas
19                                           Star Wars
20                                          The Matrix
21                                         City of God
22                               It's a Wonderful Life
23                                  The Usual Suspects
24                                               Se7en
25                                   Life Is Beautiful
26                        Once Upon a Time in the West
27                            The Silence of the Lambs
28                              Leon: The Professional
29                                         City Lights
..                                                 ...
949                                         Home Alone
950                                              Bound
951                                      Sleepy Hollow
952                                       Pirate Radio
953                              The NeverEnding Story
954                                              X-Men
955                                   Zero Dark Thirty
956                           Manhattan Murder Mystery
957                        National Lampoon's Vacation
958                                 My Sister's Keeper
959                               Deconstructing Harry
960                                   The Way Way Back
961                                             Capote
962                                 Driving Miss Daisy
963                                    La Femme Nikita
964                                            Lincoln
965                                          Limitless
966                                 The Simpsons Movie
967                                           The Rock
968                                The English Patient
969                                Law Abiding Citizen
970                                        Wonder Boys
971                                 Death at a Funeral
972                                     Blue Valentine
973                              The Cider House Rules
974                                            Tootsie
975                        Back to the Future Part III
976    Master and Commander: The Far Side of the World
977                                        Poltergeist
978                                        Wall Street

[979 rows x 1 columns]

In [5]:
df[['genre', 'title', 'duration']]

         genre                                              title  duration
0        Crime                           The Shawshank Redemption       142
1        Crime                                      The Godfather       175
2        Crime                             The Godfather: Part II       200
3       Action                                    The Dark Knight       152
4        Crime                                       Pulp Fiction       154
5        Drama                                       12 Angry Men        96
6      Western                     The Good, the Bad and the Ugly       161
7    Adventure      The Lord of the Rings: The Return of the King       201
8    Biography                                   Schindler's List       195
9        Drama                                         Fight Club       139
10   Adventure  The Lord of the Rings: The Fellowship of the Ring       178
11      Action                                          Inception       148
12      Action     Star Wars: Episode V - The Empire Strikes Back       124
13       Drama                                       Forrest Gump       142
14   Adventure              The Lord of the Rings: The Two Towers       179
15   Adventure                                       Interstellar       169
16       Drama                    One Flew Over the Cuckoo's Nest       133
17       Drama                                      Seven Samurai       207
18   Biography                                         Goodfellas       146
19      Action                                          Star Wars       121
20      Action                                         The Matrix       136
21       Crime                                        City of God       130
22       Drama                              It's a Wonderful Life       130
23       Crime                                 The Usual Suspects       106
24       Drama                                              Se7en       127
25      Comedy                                  Life Is Beautiful       116
26     Western                       Once Upon a Time in the West       175
27       Drama                           The Silence of the Lambs       118
28       Crime                             Leon: The Professional       110
29      Comedy                                        City Lights        87
..         ...                                                ...       ...
949     Comedy                                         Home Alone       103
950      Crime                                              Bound       108
951      Drama                                      Sleepy Hollow       105
952     Comedy                                       Pirate Radio       117
953  Adventure                              The NeverEnding Story       102
954     Action                                              X-Men       104
955      Drama                                   Zero Dark Thirty       157
956     Comedy                           Manhattan Murder Mystery       104
957     Comedy                        National Lampoon's Vacation        98
958      Drama                                 My Sister's Keeper       109
959     Comedy                               Deconstructing Harry        96
960     Comedy                                   The Way Way Back       103
961  Biography                                             Capote       114
962     Comedy                                 Driving Miss Daisy        99
963     Action                                    La Femme Nikita       118
964  Biography                                            Lincoln       150
965    Mystery                                          Limitless       105
966  Animation                                 The Simpsons Movie        87
967     Action                                           The Rock       136
968      Drama                                The English Patient       162
969      Crime                                Law Abiding Citizen       109
970      Drama                                        Wonder Boys       107
971     Comedy                                 Death at a Funeral        90
972      Drama                                     Blue Valentine       112
973      Drama                              The Cider House Rules       126
974     Comedy                                            Tootsie       116
975  Adventure                        Back to the Future Part III       118
976     Action    Master and Commander: The Far Side of the World       138
977     Horror                                        Poltergeist       114
978      Crime                                        Wall Street       126

[979 rows x 3 columns]

In [6]:
df.iloc[0,0]

9.3

In [7]:
df.iloc[2,1]

'The Godfather: Part II'

In [8]:
df.loc[3, 'genre']

'Action'

In [9]:
df.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [11]:
df.iloc[0:2, 0:4]

   star_rating                     title content_rating  genre
0          9.3  The Shawshank Redemption              R  Crime
1          9.2             The Godfather              R  Crime

In [12]:
df['content_rating'].unique()

array(['R', 'PG-13', 'NOT RATED', 'PG', 'UNRATED', 'APPROVED', 'PASSED',
       'G', 'X', nan, 'TV-MA', 'GP', 'NC-17'], dtype=object)